name: Publish NodeJS Package

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to GitHub Packages
      - name: Configure NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Configure Package Name
        run: |
          jq '.name |= "github-runners"' package.json

      - name: Build
        run: |
          npm ci
          npm run build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure NodeJS
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@zerocube'
      
      - name: Configure Package Name
        run: |
          jq '.name |= "@zerocube/github-runners"' package.json

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
